<|"Elementary Arithmetic" -> List["List", "Plus", "Times", "Power","FullForm"],
"Introducing Functions" -> List["List", "Subtract", "Times", "Plus", "Divide", "Power", "Max","FullForm"],
"First Look at Lists" -> List["List", "Range", "Reverse", "Join", "ListPlot",
								"Association", "Automatic", "AxesLabel", "Axis", 
								"BinomialDistribution", "Cos", "Filling", "FullForm", "Function", 
								"Hue", "Labeled", "Log", "Map", "Medium", "PDF", "Pi", "PlotLegends", 
								"PlotStyle", "Plus", "PointSize", "Power", "Prime", "Quantity", 
								"Rule", "RuleDelayed", "Sin", "Slot", "Sqrt", "Style", "Table", 
								"Times"],
"Displaying Lists" -> List["List", "BarChart", "PieChart", "Range", "Reverse", "Column", "NumberLinePlot", "Table", "Join", "ListLinePlot", "Times", "Power", "Accumulate", "Association", "Automatic", "Axes", "AxesLabel", 
		"Axis", "Center", "ChartElementFunction", "ChartElements",
		"ChartLabels", "ChartLegends", "ChartStyle", "Cos", "Disk", "False", 
		"Filling", "Frame", "FullForm", "Graphics", "ImageSize", "Infinity", 
		"Interval", "Less", "ListPlot", "MatrixForm", "Out", "Pi", 
		"PlotLegends", "Plus", "Prime", "Quantity", "RandomReal", "Rule", 
		"RuleDelayed", "SectorOrigin", "Sin", "True"],
"Operations on Lists" -> List["List", "Reverse", "Power", "Range", "Total", "ListPlot", "Sort", "Join", "Plus", "Length", "IntegerDigits", "First", "Take", "Max", "Count", "Part", "ListLinePlot", "Drop", "Times", "Last", "PieChart",
		"Accumulate", "All", "Association", "Automatic", "Axes", "AxesLabel", 
		"Axis", "BinomialDistribution", "Blank", "ChartElementFunction",
		"ChartLabels", "ChartLegends", "ChartStyle", "Cos", "False", 
		"Filling", "Frame", "FullForm", "Function", "Greater", "Hue", 
		"Infinity", "Key", "Labeled", "Less", "Log", "Map", "Medium", 
		"MixedRadix", "PDF", "Pi", "PlotLegends", "PlotStyle", "PointSize", 
		"Prime", "Quantity", "RandomReal", "Rule", "RuleDelayed", 
		"SectorOrigin", "Set", "Sin", "Slot", "Span", "Sqrt", "Style", 
		"Symbol", "Table", "True"
],
"Making Tables" -> List["List", "Table", "Power", "NumberLinePlot", "Range", "BarChart", "IntegerDigits", "ListLinePlot", "Length", "First", "Plus", "Times", "Column", "Last", "Total",
	"Accumulate", "Association", "Automatic", "Axes", "AxesLabel", 
	"Axis", "Center", "ChartElementFunction", "ChartElements", 
	"ChartLabels", "ChartLegends", "ChartStyle", "Cos", "Disk", "False", 
	"Filling", "Frame", "FullForm", "Graphics", "ImageSize", "Infinity", 
	"Interval", "Less", "ListPlot", "MatrixForm", "MixedRadix", "Out", 
	"Pi", "PlotLegends", "Prime", "Quantity", "RandomReal", "Rule", 
	"Sin", "True"
],
"Colors and Styles" -> List["List", "Red", "Yellow", "Green", "Column", "ColorNegate", "Orange", "Table", "Hue", "RGBColor", "Blend", "Pink", "Style", "Purple", "Power", "Part", "Plus", "IntegerDigits", "Times", "Join", "Reverse", "White", "Bold", "Italic",
	"All", "Association", "Automatic", "AxesStyle", "Background", 
	"Black", "Blue", "Center", "Circle", "ColorFunction", "ColorSpace", 
	"Disk", "Frame", "FullForm", "Function", "Graphics", "Graphics3D", 
	"Grid", "Image", "ImageSize", "InputForm", "Interleaving", "Key", 
	"ListPlot", "Magenta", "MatrixForm", "MetaInformation", "MixedRadix", 
	"None", "Out", "Pi", "Plain", "Plot", "Plot3D", "PlotStyle", "Prime", 
	"Rule", "RuleDelayed", "Set", "Sin", "Slot", "Span", "Sphere", 
	"Sqrt", "Text", "Thick", "True"],
"Basic Graphics Objects" -> List["List", "Graphics", "RegularPolygon", "Style", "Circle", "Red", "Table", "Disk", "Hue", "Column", "Green", "Pink", "Graphics3D", "Cylinder", "Purple", "Reverse",
	"ArcLength", "Area", "Arrow", "Arrowheads", "Association", "Axis", 
	"BesselJ", "Black", "Blue", "Center", "ColorFunction", 
	"CompoundExpression", "Cos", "Cuboid", "Dashed", "Directive", 
	"EdgeForm", "Filling", "FullForm", "GraphPlot", "Italic", 
	"Large", "Line", "ListPlot", "MatrixForm", "Mesh", "Mod", "None", 
	"Null", "Opacity", "Orange", "Out", "ParametricPlot3D", "Pi", "Plot", 
	"Plot3D", "PlotStyle", "Plus", "Polygon", "PolyhedronData", "Power", 
	"Prime", "Rectangle", "RegionCentroid", "ReliefPlot", "Rule", 
	"RuleDelayed", "Set", "Sin", "Sphere", "Sqrt", "Subscript", "Text", 
	"Thick", "Times", "Volume", "Yellow"
],
"Interactive Manipulation" -> List["List", "Manipulate", "Range", "ListPlot", "Column", "Table", "Graphics", "Style", "Disk", "Hue", "RGBColor", "IntegerDigits", "Times", "Power", "RegularPolygon", "Red", "Yellow", "Blue", "PieChart", "BarChart", "NumberLinePlot", "Graphics3D", "Sphere", "Plus", "ListLinePlot",
"Accumulate", "Area", "Arrow", "Arrowheads", "Automatic", "Axes", 
"AxesLabel", "Axis", "BesselJ", "BinomialDistribution", "Black", 
"Center", "ChartElementFunction", "ChartElements", "ChartLabels", 
"ChartLegends", "ChartStyle", "Circle", "ColorFunction", 
"CompoundExpression", "Cos", "Cuboid", "Cylinder", "Dashed", 
"Directive", "EdgeForm", "Evaluate", "Factor", "False", "Filling", 
"Frame", "FullForm", "Function", "GraphPlot", "Green", "ImageSize", 
"Infinity", "Interval", "Italic", "Labeled", "Large", "Less", "Line", 
"Log", "Map", "MatrixForm", "Medium", "Mesh", "MixedRadix", "Mod", 
"None", "Null", "Opacity", "Orange", "Out", "ParametricPlot3D", 
"PDF", "Pi", "Pink", "Plot", "Plot3D", "PlotLegends", "PlotStyle", 
"PointSize", "Polygon", "PolyhedronData", "Prime", "Purple", 
"Quantity", "RandomReal", "Rectangle", "RegionCentroid", 
"ReliefPlot", "Rule", "SectorOrigin", "Set", "Sin", "Slot", "Sqrt", 
"Subscript", "Text", "Thick", "True", "Volume"
],
"Images" -> List["List", "ColorNegate", "EdgeDetect", "Image", "Rule", "ColorSpace", "Interleaving", "True", "Manipulate", "Blur", "Table", "ImageCollage", "Binarize", "ImageAdd", "Automatic", "ImageSize", "None", "Graphics3D", "Sphere", "Graphics", "Style", "RegularPolygon", "Purple", "Disk", "Hue", "Red",
	"All", "And", "Apply", "Area", "Arrow", "Arrowheads", "AxesStyle", 
	"Axis", "Background", "BesselJ", "Black", "Blue", "Boxed", 
	"BoxRatios", "Circle", "ClipRange", "ColorFunction", "Column", 
	"CompoundExpression", "ContourPlot", "ContourShading", "Cos", 
	"CountryData", "Cuboid", "Cylinder", "Dashed", "Directive", 
	"Dynamic", "E", "EdgeForm", "EntityValue", "Evaluate", "Factor", 
	"False", "Filling", "Frame", "FullForm", "Function", "GraphPlot", 
	"Greater", "Green", "Grid", "Head", "If", "Image3D", "ImagePadding", 
	"ImageResolution", "Implies", "InputForm", "Italic", 
	"ItemSize", "Large", "Line", "ListPlot", "Magnification", "Map", 
	"MatrixForm", "MatrixQ", "Medium", "Mesh", "MeshShading", "Method", 
	"Mod", "Nest", "NIntegrate", "Not", "Null", "Opacity", "Options", 
	"Orange", "Out", "ParametricPlot3D", "Pi", "Pink", "Plot", "Plot3D", 
	"PlotRange", "PlotStyle", "Plus", "Polygon", "PolyhedronData", 
	"Power", "Prime", "RandomReal", "Rectangle", "RegionCentroid", 
	"ReliefPlot", "ReplaceAll", "RGBColor", "Scaled", "Set", "Sin", 
	"Slider", "Slot", "Small", "Sqrt", "Subscript", "TaggingRules", 
	"Tan", "Text", "Thick", "Times", "Tiny", "ToExpression", "TreeForm", 
	"VertexLabeling", "Volume", "Yellow"

],
"Strings and Text" -> List["List", "StringJoin", "ToUpperCase", "Alphabet", "StringReverse", "Table", "StringTake", "Column", "StringLength", "BarChart", "TextWords", "WikipediaData", "Length", "First", "TextSentences", "Max", "WordList", "Count", "ListLinePlot", "Take", "WordCloud", "Characters", "RomanNumeral", "Range", "LetterNumber", "FromLetterNumber", "Plus", "Transliterate", "ColorNegate", "Rasterize", "Style", "Manipulate", "EdgeDetect", "Blur", "IntegerName", "Part", "ImageAdd",
	"Accumulate", "All", "Association", "Automatic", "Axes", "AxesLabel", 
	"AxesStyle", "Axis", "Background", "Blank", "Blue", "Boxed", 
	"BoxRatios", "Center", "ChartElementFunction", "ChartElements", 
	"ChartLabels", "ChartLegends", "ChartStyle", "Circle", "ClipRange", 
	"ColorSpace", "CompoundExpression", "Cos", "CountryData", "Cylinder", 
	"Disk", "Entity", "EntityValue", "Factor", "False", "Filling", 
	"Frame", "FullForm", "Function", "GeoDisk", "Graph", "Graphics", 
	"Graphics3D", "Image", "Image3D", "ImageResolution", "ImageSize", 
	"Infinity", "InputForm", "Interleaving", "Italic", "Key", 
	"LightYellow", "ListPlot", "Magnification", "Map", "MatrixForm", 
	"MaxItems", "None", "Null", "Orange", "Out", "Pi", "Pink", "Placed", 
	"Plot", "PlotLegends", "Power", "Prime", "Quantity", "RandomInteger", 
	"RandomReal", "RasterSize", "Red", "RGBColor", "Rule", "Set", 
	"Shallow", "Sin", "Slot", "Small", "Span", "Sphere", "Sqrt", 
	"StringSplit", "Symbol", "TaggingRules", "Text", "Thick", "Times", 
	"ToExpression", "Tooltip", "True", "VertexLabels", "VertexStyle"
],
"Sound" -> List["List", "Sound", "SoundNote", "Table", "Reverse", "Times", "Power", "Part", "IntegerDigits", "Length", "Characters", "LetterNumber", "StringLength", "IntegerName",
	"All", "Association", "Column", "Entity", "FullForm", "InputForm", 
	"Key", "ListPlot", "MatrixForm", "MixedRadix", "Out", "Play", "Plus", 
	"Prime", "Rule", "RuleDelayed", "Set", "Sin", "Span", "StringJoin"],
"Arrays or Lists of Lists" -> List["List", "Grid", "Table", "Times", "RomanNumeral", "Style", "StringJoin", "FromLetterNumber", "PieChart", "NumberLinePlot", "ListLinePlot", "BarChart", "ArrayPlot", "Hue", "Power", "StringLength", "Plus"],
	"Coordinates and Graphics" -> List["List", "Graphics", "Table", "Circle", "Style", "Point", "Manipulate", "Graphics3D", "Sphere", "Times", "Power", "RGBColor", "RegularPolygon", "Line", "Plus", "Opacity", "Take", "IntegerDigits", "ArcLength", "Area", "Arrow", "Arrowheads", "Association", "Axis", 
					"BesselJ", "Black", "Blue", "ColorFunction", "Column", 
					"CompoundExpression", "Cos", "Cuboid", "Cylinder", "Dashed", 
					"Directive", "Disk", "EdgeForm", "Factor", "Filling", 
					"FullForm", "GraphPlot", "Green", "Italic", "Large", "ListPlot", 
					"MatrixForm", "Mesh", "MixedRadix", "Mod", "None", "Null", "Orange", 
					"Out", "ParametricPlot3D", "Pi", "Pink", "Plot", "Plot3D", 
					"PlotStyle", "PointSize", "Polygon", "PolyhedronData", "Prime", 
					"Purple", "Rectangle", "Red", "RegionCentroid", "RegionMeasure", 
					"ReliefPlot", "Rule", "Set", "Sin", "Small", "Sqrt", "Subscript", 
					"Text", "Thick", "ToExpression", "Volume", "Yellow"],
"Real‐World Data" -> List["List", "Throw", "RowBox", "TemplateBox", "Entity", "EntityValue", "EntityClass", "All", "BarChart", "ImageCollage", "EdgeDetect", "Times", "Power", "DominantColors", "PieChart", "ImageAdd", "ColorNegate",
			"Apply", "Automatic", "AxesStyle", "Background", "Blank", "Boxed", 
			"BoxRatios", "Catch", "CellPrint", "CellTags", 
			"ChartElementFunction", "ChartElements", "ChartLabels", 
			"ChartLegends", "ChartStyle", "ClipRange", "ColorSpace", 
			"CompoundExpression", "CountryData", "Disk", "DisplayForm", 
			"DisplayFunction", "Do", "EntityClassList", "EntityList", 
			"EntityProperty", "Exp", 
			"ExpressionCell", "Factorial", "False", "FullForm", "Function", 
			"Graphics", "Greater", "If", "Image", "Image3D", "ImagePadding",
			"ImageSize", "InputForm", "Interleaving", "InterpretationFunction", 
			"Interval", "Magnification", "Map", "None",
			"Null", "Out", "Part", "Pattern", "Plot3D", "PlotRange", "Plus", 
			"Quantity", "Range", "RGBColor", "Rule", "RuleDelayed", 
			"SectorOrigin", "Set", "SetDelayed", "Shallow", "Short", "Slot", 
			"SuperscriptBox", "Take", "TakeLargest", "True", "UnderoverscriptBox"
],
"Units" -> List["List", "UnitConvert", "Quantity", "Times", "Power", "Entity", "EntityProperty", "CurrencyConvert", "Plus", "EntityClass", "All", "Rotate", "Degree", "Table", "Style", "Manipulate", "Graphics", "Line", "AnglePath", "IntegerDigits", "Part", "Alphabet",
	"ArcLength", "Arrow", "Arrowheads", "Association", "Axis", "BesselJ", 
	"Black", "Blue", "BSplineCurve", "CapForm", "Circle", 
	"ColorFunction", "Column", "CompoundExpression", "CompressedData", 
	"ConstantArray", "Cos", "Cuboid", "Dashed", "DatedUnit", "Disk", 
	"EdgeForm", "EntityClassList", "EntityList", "EntityProperties", 
	"EntityValue", "Evaluate", "Exp", "Factor", "FilledCurve", "Filling", 
	"FullForm", "Function", "GeometricTransformation", "Graphics3D", 
	"GraphPlot", "GrayLevel", "Green", "ImageSize", "InputForm", 
	"Interval", "Italic", "Key", "LakeData", "Large", "ListPlot", 
	"MatrixForm", "Medium", "MixedRadix", "Mod", "N", "Null", "Opacity", 
	"Orange", "Out", "Pink", "Plot", "Plot3D", "PlotRange", "Polygon", 
	"Prime", "Purple", "Rectangle", "Red", "RegionCentroid", 
	"ReliefPlot", "RGBColor", "Rule", "Set", "Shallow", "Sin", "Slot", 
	"Span", "Sphere", "SplineClosed", "Sqrt", "Subscript", "Take", 
	"TakeLargest", "Text", "Thick", "True", "Yellow"
],
"Geocomputation" -> List["List", "GeoDistance", "Entity", "Times", "Power", "UnitConvert", "Quantity", "GeoGraphics", "GeoListPlot", "GeoPath", "GeoDisk", "GeoNearest", "GeoPosition", "EntityValue", "Plus", "Part", "EntityClass", "Style", "Thick", "Red", "Blue", "Table",
	"All", "Arrow", "Association", "Black", "BlankSequence", "Circle", 
	"Column", "DeleteCases", "Disk", "EdgeForm", "EntityClassList", 
	"EntityList", "EntityProperty", "FaceForm", "Frame", "FrameStyle", 
	"FullForm", "Function", "GeoBackground", "GeoMarker", 
	"GeoPositionXYZ", "GeoProjection", "GeoRange", "GeoRangePadding", 
	"GeoStyling", "Graphics", "Graphics3D", "Grid", "Here", "InputForm", 
	"Interval", "Italic", "Key", "Line", "ListPlot", "MatrixForm", 
	"None", "Orange", "Out", "Pink", "Plot", "PlotStyle", "Polygon", 
	"Prime", "Rule", "SatelliteData", "Set", "Shallow", "Short", "Sin", 
	"Slot", "Span", "Sphere", "Sqrt", "Take", "TakeLargest", "Text", 
	"Thin", "True", "With"
],
"Dates and Times" -> List["List", "Plus", "Times", "DateObject", "DayName", "Today", "Quantity", "LocalTime", "Entity", "Sunset", "Here", "Sunrise", "MoonPhase", "Table", "AirTemperatureData", "Yesterday", "TimeObject", "DateListPlot", "WordFrequencyData", "UnitConvert", "ListLinePlot", "Manipulate", "Column",
	"Accumulate", "Automatic", "Axes", "AxesLabel", "Axis", "Center", 
	"CompoundExpression", "Cos", "DateList", "EntityList", 
	"EntityProperty", "EntityValue", "Factor", "False", "Filling", 
	"FinancialData", "Frame", "FullForm", "Function", "GeoPosition", 
	"InputForm", "Joined", "ListPlot", "MatrixForm", "Now", "Null", 
	"Out", "Pi", "Plot", "PlotLabels", "PlotLegends", "Power", "Prime", 
	"RandomReal", "Range", "Rule", "Set", "Sin", "Slot", "Take", 
	"TimeSeries", "Tomorrow", "True", "UnitSystem"
],
"Options" -> List["List", "ListPlot", "Range", "Rule", "PlotTheme", "Filling", "Axis", "Background", "Yellow", "GeoListPlot", "Entity", "GeoRange", "All", "GeoGraphics", "EntityClass", "GeoBackground", "GeoLabels", "Automatic", "Grid", "Table", "Style", "Times", "White", "Black", "Graphics", "Disk", "ImageSize", "RegularPolygon", "AspectRatio", "Manipulate", "Circle", "Frame", "ListLinePlot", "StringLength", "RomanNumeral", "PlotRange", "Max", "True", "Power", "GeoDisk", "Quantity", "DateListPlot", "AirTemperatureData", "Plus", 
	"Accumulate", "And", "Apply", "ArcLength", "Area", "Arrow", 
	"Arrowheads", "Axes", "AxesLabel", "AxesStyle", "BaselinePosition", 
	"BesselJ", "BinomialDistribution", "BlankSequence", "Blue", "Bottom", 
	"Boxed", "Center", "ClippingStyle", "ColorFunction", "Column", 
	"CompoundExpression", "Cos", "CountryData", "Dashed", "Dated", 
	"DateObject", "DeleteCases", "Directive", "Dynamic", "E", "EdgeForm", 
	"EntityClassList", "EntityList", "EntityProperty", "EntityValue", 
	"Evaluate", "Exp", "FaceForm", "Factor", "False", "FillingStyle", 
	"FinancialData", "FrameStyle", "Full", "FullForm", "Function", 
	"GeoDistance", "GeoMarker", "GeoPath", "GeoPosition", 
	"GeoProjection", "GeoRangePadding", "GeoRegionValuePlot", 
	"GeoStyling", "Graphics3D", "GraphPlot", "Greater", "Green", "Hue", 
	"If", "Implies", "InputForm", "Interval", "Italic", "ItemSize", 
	"Joined", "Labeled", "Large", "Less", "LightBlue", "LightRed", 
	"Line", "Log", "Map", "MatrixForm", "MatrixQ", "Mean", "Medium", 
	"Mesh", "Method", "Mod", "Nest", "NIntegrate", "None", "Not", "Null", 
	"Opacity", "Options", "Orange", "Out", "Part", "PDF", "Pi", "Pink", 
	"Plot", "Plot3D", "PlotLabels", "PlotLegends", "PlotRangeClipping", 
	"PlotStyle", "Point", "PointSize", "Polygon", "Prime", "Purple", 
	"RandomInteger", "RandomReal", "Rectangle", "Red", "RegionCentroid", 
	"RegionFunction", "ReliefPlot", "ReplaceAll", "Scaled", "Sequence",
	"Set", "Shallow", "Sin", "Slider", "Slot", "Small", "Sphere", "Sqrt", 
	"Subscript", "Take", "TakeLargest", "Tan", "Text", "Thick", 
	"TimeSeries", "Tiny",  "Top", "UnitSystem", "With"
],
"Graphs and Networks" -> List["Accumulate", "All", "Arrow", "Arrowheads", "Automatic", "Axes", 
								"AxesLabel", "AxesStyle", "Axis", "Background", "Binarize", "Black", 
								"Blank", "Block", "Blue", "Boxed", "BoxRatios", "Circle", 
								"ColorSpace", "Column", "CommunityGraphPlot", "CompleteGraph", 
								"CompoundExpression", "Cos", "Cylinder", "Dashed", "Dimensions", 
								"DirectedEdge", "Directive", "Disk", "EdgeList", "EdgeShapeFunction", 
								"EdgeStyle", "ExampleData", "False", "Filling", 
								"FindGraphCommunities", "FindShortestPath", "Flatten", "Frame", 
								"Framed", "FullForm", "Function", "Graph", "GraphElementData", 
								"GraphHighlightStyle", "Graphics", "Graphics3D", "GraphLayout", 
								"GrayLevel", "Green", "Grid", "GridGraph", "GridLinesStyle", 
								"HighlightGraph", "Image", "Image3D", "ImageData", "ImagePadding", 
								"ImageResolution", "ImageSize", "IntegerDigits", "Interleaving", 
								"Italic", "Labeled", "Large", "Left", "LightYellow", "List", 
								"ListLinePlot", "ListPlot", "MatrixForm", "Max", "Medium", 
								"MixedRadix", "None", "Null", "Orange", "Out", "Part", "PathGraph", 
								"Pattern", "Pi", "Pink", "Plot", "PlotLabel", "PlotLegends", 
								"PlotStyle", "Plus", "Polygon", "Power", "Prime", "Property", 
								"Quantity", "RandomReal", "Range", "Rasterize", "RasterSize", "Red", 
								"ReplaceAll", "Rule", "Set", "SetDelayed", "Sin", "Slot", "Small", 
								"Span", "Sphere", "Sqrt", "Style", "Table", "Text", "Thick", "Times", 
								"Top", "Total", "True", "UndirectedEdge", "UndirectedGraph", 
								"VertexLabels", "VertexShapeFunction", "VertexSize", "VertexStyle", 
								"White"],
"Machine Learning" -> List["List", "LanguageIdentify", "ImageIdentify", "EntityValue", "Entity", "EntityProperty", "Table", "Blur", "Classify", "Nearest", "WordList", "Red", "First", "Power", "EntityClass", "NearestNeighborGraph", "Hue", "Rule", "VertexLabels", "All", "FindClusters", "Rasterize", "Style", "FromLetterNumber", "TextRecognize", "Dendrogram", "FeatureSpacePlot", "ToUpperCase", "WikipediaData", "Pink", "Flatten", "Times", "Pi", "Join","Alphabet", "Association", "Automatic", "Background", "Blue", "Boxed", "Circle", "ColorSpace", "Column", "CompleteGraph", "CompoundExpression", "Cylinder", "Dimensions", "Disk", "EditDistance", "EntityClassList", "EntityList", "EntityProperties", "Exclusions", "Exp", "False", "FullForm", "Function", "GeoDisk", "Graph", "Graphics", "Graphics3D", "GraphicsComplex", "Green", "HighlightImage", "Image", "ImagePartition", "ImageResolution", "ImageSize", "InputForm", "Interleaving", "Interval", "Italic", "LakeData", "Left", "LightYellow", "ListPlot", "Magnification", "Map", "MatrixForm", "MaxItems", "MetaInformation", "Missing", "N", "None", "Null", "Orange", "Out", "Part", "Placed", "Plot", "Plot3D", "PlotRange", "PlotStyle", "Plus", "Polygon", "Prime", "Quantity", "RandomReal", "Range", "RasterSize", "ReplaceAll", "RGBColor", "Round", "Set", "Shallow", "Short", "Sin", "Slot", "Small", "Span", "Sphere", "Sqrt", "StringSplit", "Subscript", "TaggingRules", "Take", "TakeLargest", "Text", "TextSentences", "Thick", "Tooltip", "True", "UndirectedEdge", "VertexStyle", "VertexWeight"],
"More about Numbers" -> List["List", "N", "Sqrt", "ListPlot", "Table", "Graphics", "Line", "AnglePath", "Times", "Pi", "Mod", "Power", "ListLinePlot", "Round", "Graph", "Rule", "Style", "Circle", "Prime", "Log", "Plus", "Sound", "SoundNote", "ArrayPlot", "Total", "Degree"],
"More Forms of Visualization" -> List["List", "ListLinePlot", "Table", "Power", "Prime", "Rule", "Filling", "Axis", "Mesh", "True", "MeshStyle", "Red", "ListPlot3D", "GeoElevationData", "GeoDisk", "Entity", "Quantity", "ReliefPlot", "Mod", "Histogram", "Plus", "Times", "First", "IntegerDigits", "StringLength", "RomanNumeral", "TextSentences", "WikipediaData", "Total", "ImageData", "Binarize", "Rasterize", "Style", "TextWords"],
"Ways to Apply Functions" -> List["List", "Map", "Range", "Framed", "Alphabet", "ColorNegate", "EntityValue", "EntityClass", "All", "GeoGraphics", "EntityList", "ImageCollage", "Binarize", "EntityProperty", "Column", "DominantColors", "Total", "LetterNumber", "Characters"],
"Pure Anonymous Functions" -> List["List", "Map", "Function", "Power", "Slot", "Range", "Blend", "Red", "Yellow", "Green", "Blue", "Framed", "Column", "ToUpperCase", "Alphabet", "Style", "Rule", "Background", "Grid", "EntityValue", "EntityList", "EntityClass", "Frame", "All", "WordCloud", "WikipediaData", "Histogram", "StringLength", "TextWords", "GeoListPlot", "GeoRange", "Plus"],
"Applying Functions Repeatedly" -> List["List", "NestList", "Blur", "Rasterize", "Style", "Function", "Framed", "Slot", "Rule", "Background", "Rotate", "Times", "Degree", "ListLinePlot", "Plus", "N", "Nest", "Power", "Sqrt", "Graphics", "Line", "ArrayPlot", "Mod", "Join", "NestGraph", "Entity", "VertexLabels", "All", "Graphics3D"],
"Tests and Conditionals" -> List["List", "Greater", "Power", "Select", "Range", "Function", "Less", "Total", "IntegerDigits", "Slot", "Map", "If", "PrimeQ", "Style", "Red", "WordList", "Equal", "StringTake", "StringReverse", "Array", "Prime", "Last", "RomanNumeral", "Not", "MemberQ", "Characters", "Table", "IntegerName", "First", "TextWords", "WikipediaData", "StringLength", "NestList", "EvenQ", "Times", "Plus", "WordCloud", "And", "GreaterEqual", "Unequal", "LetterNumber", "Mod", "White", "Black", "EntityList", "EntityClass", "All", "Entity", "ArrayPlot"],
"More about Pure Functions" -> List["List", "Array", "Prime", "Function", "Plus", "Slot", "Times", "Grid", "FoldList", "Range", "ImageAdd", "Table", "Graphics", "Style", "RegularPolygon", "Opacity", "If", "GreaterEqual"],
"Rearranging Lists" -> List["List", "Thread", "Rule", "Alphabet", "Range", "Length", "Grid", "Partition", "IntegerDigits", "Power", "Frame", "All", "Characters", "StringTake", "WikipediaData", "ListLinePlot", "Flatten", "Map", "ArrayPlot", "NestList", "Function", "ArrayFlatten", "Slot", "Select", "Table", "Sqrt", "Plus", "IntegerQ", "Last", "Max", "Split", "GatherBy", "Array", "IntegerName", "SortBy", "Take", "WordList", "StringReverse", "First", "StringLength", "Complement", "Intersection", "EntityList", "EntityClass", "Transpose", "Permutations", "Union", "StringJoin", "Tuples", "LetterNumber", "LetterQ", "Mod", "Abs", "Riffle", "Blend", "Red", "Green", "Blue", "ImageSize"],
"Parts of Lists" -> List["List", "Take", "IntegerDigits", "Power", "Part", "Alphabet", "Span", "Range", "Length", "ListLinePlot", "Table", "TakeSmallest", "Join", "Flatten", "Position", "TextWords", "WikipediaData", "Histogram", "Map", "Function", "Characters", "Slot", "WordList", "ReplacePart", "Thread", "Rule", "Red", "If", "Less", "First", "Nothing", "Array", "Prime", "Grid", "NestList", "TakeLargestBy", "StringLength", "IntegerName", "Count"],
"Patterns" -> List["List", "Cases", "IntegerDigits", "Range", "BlankSequence", "Pattern", "Blank", "Power", "Alternatives", "ReplaceAll", "Rule", "Gray", "Orange", "Red", "Characters", "Nothing"],
"Expressions and Their Structure" -> List["List", "Head", "ListPlot", "Range", "Apply", "Times", "Tuples", "Map", "TreeForm", "NestList", "Function", "Power", "Slot", "Union", "Cases", "Flatten", "Table", "Plus", "Blank", "Integer", "Graph", "Rule", "Partition", "Mod", "TextWords", "WikipediaData", "VertexLabels", "All"],
"Associations" -> List["List", "Values", "KeySort", "Counts", "IntegerDigits", "Power", "BarChart", "Rule", "ChartLabels", "Automatic", "StringTake", "WordList", "TakeLargest", "N", "Function", "Times", "Slot", "LetterCounts", "WikipediaData", "Keys", "TextWords", "ExampleData"],
"Natural Language Understanding" -> List["All", "Alphabet", "Association", "Automatic", "Blank", "Blue",  
											"Cases", "ColorSpace", "Column", "CommonName", "CommunityGraphPlot", 
											 "CompoundExpression", "ContentObject", "CountryData", "Counts",  
											"DelimitedSequence", "Dimensions", "Entity", "EntityClass",  
											"EntityClassList", "EntityList", "EntityProperties",  
											"EntityProperty", "EntityValue", "ExampleData", "Except", "FindGraphCommunities", "First", 
											"Flatten",  "FullForm", "Function", "GeoDisk", "Graph", "Image", 
											"Indeterminate",  "InputForm", "Integer", "IntegerName", 
											"Interleaving", "Interpreter",  "Interval", "Keys", "LakeData", 
											"Length", "Less", "List", "ListPlot",  "Map", "MatchQ", 
											"MatrixForm", "MaxItems", "Missing", "None", "Null",  "OddQ", 
											"Out", "Part", "Pattern", "Permutations", "Placed", "Plus",  
											"Positive", "Power", "Prime", "Quantity", "RandomInteger",  
											"RandomReal", "Red", "Restricted", "Rule", "Set", "SetDelayed",  
											"Shallow", "Short", "Slot", "Span", "StringJoin", "StringSplit",  
											"StringTake", "Style", "Symbol", "Table", "Take", "TakeLargest",  
											"TextCases", "TextSentences", "TextStructure", "Times", "Today",  
											"Tomorrow", "Tooltip", "ToString", "ToUpperCase", "UpTo", "URL",  
											"VertexLabels", "VertexStyle", "WikipediaData", "WordCloud",  
											"WordList", "WordTranslation", "Yesterday"],
"Layout and Display" -> List["List", "Map", "Function", "Style", "Slot", "Rule", "Background", "If", "EvenQ", "Yellow", "LightGray", "Range", "PrimeQ", "Framed", "Labeled", "Mod", "GraphicsGrid", "Table", "Graphics", "Disk", "PieChart", "EntityList", "EntityClass", "Legended", "Partition", "Counts", "IntegerDigits", "Power", "GraphicsRow", "WordCloud", "DeleteStopwords", "WikipediaData"],
"Assigning Names to Things" -> List["List", "Module", "Set", "Range", "Plus", "Power", "Column", "Sort", "Max", "Total", "EntityValue", "Entity", "EntityProperty", "ImageCollage", "Blur", "EdgeDetect", "ColorNegate", "ListLinePlot", "Join", "Reverse", "NestList", "Function", "Mod", "Times", "Slot", "Table", "StringJoin", "Characters", "CompoundExpression", "Complement", "Alphabet", "Map"],
"Immediate and Delayed Values" -> List["List", "ReplaceAll", "Plus", "Power", "Rule", "RuleDelayed","Blank", "Cos", "FullForm", "Pattern", "RandomReal", "Sin"],
"Defining Your Own Functions" -> List["List", "SetDelayed", "Pattern", "Blank", "Power", "Integer", "Graphics", "Style", "RegularPolygon", "Orange", "Times", "Plus", "CompoundExpression", "If", "EvenQ", "Black", "White", "Set", "Red", "String", "Interpreter", "Nearest", "WordList"],
"More about Patterns" -> List["List", "Cases", "Table", "IntegerDigits", "Power", "BlankNullSequence", "Pattern", "Blank", "Map", "StringJoin", "Array", "Function", "Characters", "RomanNumeral", "Slot", "SetDelayed", "Repeated", "Integer", "Equal", "Reverse", "Partition", "TextWords", "WikipediaData", "Condition", "StringTake", "Grid", "FixedPointList", "ReplaceAll", "Rule", "Greater", "ArrayPlot", "Transpose", "Range", "Times", "Plus", "Unequal", "Mod", "Factorial", "Length", "NestList", "ListLinePlot"],
"String Patterns and Templates" -> List["List", "StringReplace", "Rule", "Sort", "StringCases", "WikipediaData", "StringExpression", "DigitCharacter", "Shortest", "Pattern", "BlankSequence", "Grid", "Table", "StringTemplate", "Plus", "Select", "IntegerName", "Function", "StringMatchQ", "Slot", "BlankNullSequence", "First", "TextSentences", "RuleDelayed", "Whitespace", "LetterCharacter", "ToUpperCase", "BarChart", "KeySort", "Counts", "StringTake", "Map", "TextString", "EntityList", "EntityClass", "ChartLabels", "Automatic", "Power",
	"Above", "All", "Alternatives", "Apply", "Association", "Blank", 
	"Cases", "ChartElementFunction", "ChartElements", "ChartLegends", 
	"ChartStyle", "Column", "CompoundExpression", "Disk", "EndOfString", 
	"Entity", "EntityClassList", "EntityProperty", "EntityValue", 
	"EvenQ", "Frame", "FullForm", "GeoDisk", "Graph", "Graphics", 
	"Greater", "Here", "ImageSize", "InputForm", "Integer", "Interval", 
	"Length", "Less", "ListPlot", "MatrixForm", "MaxItems", "Method", 
	"N", "NIntegrate", "Now", "Null", "Out", "Part", "Pi", "PieChart", 
	"Placed", "Plot", "PlotRange", "Prime", "Quantity", "RandomInteger", 
	"RandomReal", "Range", "Real", "Red", "Repeated", "ReplaceAll", 
	"Set", "SetDelayed", "Shallow", "Sin", "Span", "StartOfString", 
	"StringSplit", "Symbol", "TakeLargest", "Tan", "TemplateApply", 
	"Text", "Times", "Today", "Tomorrow", "Tooltip", "Top", 
	"VertexLabels", "VertexStyle", "Yesterday"
],
"Datasets" -> List["List", "Set", "Button", "CloudGet", "Inherited", "Rule", "BaseStyle", "WordCloud", "Normal", "All", "Length", "BarChart", "ChartLabels", "Automatic", "SortBy", "Function", "Slot", "Max", "Total", "Sort", "Median", "RightComposition", "Select", "Greater", "Quantity", "Times", "Power", "Keys", "Association", "Map", "StringLength", "WikipediaData", "EntityList", "EntityClass", "ResourceData", "TakeLargest", "Histogram", "Differences", "GeoListPlot", "Span", "GeoLabels", "True", "TakeLargestBy",
		"Above", "Abs", "And", "Append", "BlankSequence", "Blue", "Cell", 
		"CellMargins", "CellPrint", "CellTags", "ChartElementFunction", 
		"ChartElements", "ChartLegends", "ChartStyle", "Circle", 
		"ColorSpace", "Column", "CompoundExpression", "Cos", 
		"CountryData", "CreateDocument", "Cylinder", "DateObject", 
		"DeleteCases", "Disk", "E", "Entity", "EntityClassList", 
		"EntityProperty", "EntityValue", "EvenQ", 
		"Exp", "ExponentialDistribution", "Factorial", "FilterRules", 
		"FontFamily", "FontSize", "FullForm", "GeoBackground", "GeoDisk", 
		"GeoRange", "GeoRegionValuePlot", "Graph", "Graphics", "Graphics3D", 
		"If", "Image", "ImageSize", "Implies", "Indeterminate", "InputField", 
		"InputForm", "Interleaving", "Interval", "Italic", "Key", "Large", 
		"Last", "Less", "MatrixQ", "MaxItems", "Method", "Missing", "Mod", 
		"Next", "NIntegrate", "None", "NormalDistribution", "Not", 
		"NotebookSelection", "Null", "Number", "Options", 
		"Orange", "Out", "Part", "Pi", "PieChart", "Placed", "Plot", 
		"Plot3D", "PlotRange", "Plus", "Position", "Print", "RandomVariate", 
		"Range", "Red", "Reduce", "ReplaceAll", "ResourceObject", 
		"RuleDelayed", "SelectionMove", "Series", "SetOptions", "Shallow", 
		"Sin", "Snippet", "SparseArray", "Sphere", "String", "StringJoin", 
		"StringSplit", "Table", "Take", "Tan", "TextCell", "TextSentences", 
		"Today", "Tomorrow", "Tooltip", "Top", "Unset", "UpTo", "URL", 
		"VertexLabels", "VertexStyle", "WeibullDistribution", "Yellow", 
		"Yesterday"
],
"Writing Good Code" -> List["List", "Total", "Table", "Times", "Plus", "Nest", "Function", "Power", "Slot", "Flatten", "Array", "ListLinePlot", "First", "Timing", "Sort", "Range"],
"Debugging Your Code" -> List["List", "Counts", "Map", "Function", "If", "Greater", "StringLength", "Slot", "StringTake", "Nothing", "WordList", "First", "Last", "Reap", "Fold", "Plus", "Times", "Sow", "Nest", "EvenQ", "Power"]|>
